INSERT INTO PUBLIC.BANK (ID, NAME) VALUES (1, 'VILLAGEBANK');

INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (1, 'DEBIT', 1);
INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (2, 'CREDIT', 1);

INSERT INTO PUBLIC.CLIENT (ID, NAME, ACCOUNT_TYPE_ID) VALUES (2, 'SIDOROV', 1);
INSERT INTO PUBLIC.CLIENT (ID, NAME, ACCOUNT_TYPE_ID) VALUES (3, 'IVANOV', 2);