INSERT INTO PUBLIC.BANK (ID, NAME) VALUES (1, 'VILLAGEBANK');

INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (1, 'DEBIT', 1);
INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (2, 'CREDIT', 1);

INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_TYPE_ID)
VALUES (1, 'PETROV', 1);
INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_TYPE_ID)
VALUES (2, 'IVANOV', 2);
INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_TYPE_ID)
VALUES (3, 'SIDOROV', 1);