INSERT INTO PUBLIC.BANK (ID, NAME) VALUES (1, 'VILLAGEBANK');

INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (1, 'DEBIT', 1);
INSERT INTO PUBLIC.ACCOUNT_TYPE (ID, NAME, BANK_ID) VALUES (2, 'CREDIT', 1);

INSERT INTO PUBLIC.ACCOUNT (ID, DATE, MINIMAL_ACCOUNT_FOR_SERVICE_FEE, SERVICE_PERCENT, SERVICE_PERIOD, VALUE) VALUES (1, '2019-07-24', 100.00, 5.0, 30, 100000.80);
INSERT INTO PUBLIC.ACCOUNT (ID, DATE, MINIMAL_ACCOUNT_FOR_SERVICE_FEE, SERVICE_PERCENT, SERVICE_PERIOD, VALUE) VALUES (2, '2019-07-24', 50.00, 10.0, 15, 20000.00);
INSERT INTO PUBLIC.ACCOUNT (ID, DATE, MINIMAL_ACCOUNT_FOR_SERVICE_FEE, SERVICE_PERCENT, SERVICE_PERIOD, VALUE) VALUES (3, '2019-07-24', 10.00, 1.0, 365, 10000.00);

INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_ID, ACCOUNT_TYPE_ID) VALUES (1, 'PETROV' , 3, 1);
INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_ID, ACCOUNT_TYPE_ID) VALUES (2, 'IVANOV' , 1, 2);
INSERT INTO PUBLIC.CLIENTS (ID, NAME, ACCOUNT_ID, ACCOUNT_TYPE_ID) VALUES (3, 'SIDOROV', 2, 1);